# After changing this file, check it on:
#   http://yaml-online-parser.appspot.com/

language: python

sudo: true

python:
  - 2.7
  - 3.5

cache: pip

env:
  - CI_REPORTS=shippable/testresults COVERAGE_REPORTS=shippable/codecoverage CODACY_PROJECT_TOKEN=43ac6a06566f42968e919830ee28de4d

build:
  ci:
    - echo $CI_REPORTS && mkdir -p $CI_REPORTS
    - echo $COVERAGE_REPORTS && mkdir -p $COVERAGE_REPORTS
    - DISPLAY=""

before_install:
  - apt-get update # --fix-missing
  - apt-get install freetype*
  - apt-get install python-dev python-tk python3-dev python3-tk
  - apt-get install pkg-config
  - apt-get install python-opencv openslide-tools
  - pip install --upgrade pip

install:
  - pip install -r requirements.txt
  - pip install -r ./tests/requirements.txt
  - pip --version ; pip freeze

script:
  - mkdir results
  # - nosetests --with-xunit --xunit-file=shippable/testresults/nosetests.xml
  - nosetests -v --exe --with-doctest --with-coverage --with-xunit --cover-package=birl --xunit-file=shippable/testresults/nosetests.xml

after_success:
  - codecov
  - coverage xml -o $COVERAGE_REPORTS/coverage.xml
  - python-codacy-coverage -r $COVERAGE_REPORTS/coverage.xml
  - coverage report
