# vim ft=yaml

# After changing this file, check it on:
#   http://yaml-online-parser.appspot.com/

language: python

sudo: true

python:
  - 2.7
  - 3.6

cache: pip

env:
  - CI_REPORTS=shippable/testresults COVERAGE_REPORTS=shippable/codecoverage CODACY_PROJECT_TOKEN=43ac6a06566f42968e919830ee28de4d

build:
  ci:
    - echo $CI_REPORTS && mkdir -p $CI_REPORTS
    - echo $COVERAGE_REPORTS && mkdir -p $COVERAGE_REPORTS

before_install:
  - apt-get update # --fix-missing
  - apt-get install freetype*
  - apt-get install python-dev python-tk
  - apt-get install pkg-config
  - apt-get install python-opencv openslide-tools
  - pip install --upgrade pip

install:
  - pip install -r requirements.txt
  - pip install nose coverage codecov pytest codacy-coverage

script:
  - mkdir results
  # - nosetests --with-xunit --xunit-file=shippable/testresults/nosetests.xml
  - nosetests -v --exe --with-doctest --with-coverage --with-xunit --cover-package=benchmark --xunit-file=shippable/testresults/nosetests.xml

  - python bm_experiments/bm_comp_perform.py -o ./results -n 1
  - python benchmark/bm_template.py -c data_images/pairs-imgs-lnds_mix.csv -o results --unique  --an_executable none

  - python bm_dataset/generate_regist_pairs_all.py -i "data_images/images/artificial_*.jpg" -l "data_images/landmarks/artificial_*.csv" -csv data_images/cover_artificial.csv --mode each2all
  # - python bm_experiments/create_real_synth_dataset.py -i data_images/images/Rat_Kidney_HE.jpg -l data_images/landmarks/Rat_Kidney_HE.csv -o data_images/synth_dataset -nb 3 --nb_jobs 1
  # - python bm_dataset/generate_regist_pairs_all.py -i "data_images/synth_dataset/*.jpg" -l "data_images/synth_dataset/*.csv" -csv data_images/cover_synth-dataset.csv --mode each2all

after_success:
  - codecov
  - coverage xml -o $COVERAGE_REPORTS/coverage.xml
  - python-codacy-coverage -r $COVERAGE_REPORTS/coverage.xml
  - coverage report