# vim ft=yaml

# After changing this file, check it on:
#   http://yaml-online-parser.appspot.com/

# See doc/travis_notes.txt for some guidelines

# this file is *not* meant to cover or endorse the use of travis, but rather to
# help confirm pull requests to this project.

env:
  global:
    - DISPLAY=""

matrix:
  # https://blog.travis-ci.com/2019-08-07-extensive-python-testing-on-travis-ci
  # https://docs.travis-ci.com/user/languages/python/
  include:
    - os: linux
      language: python
      python: 2.7
      dist: xenial  # Ubuntu 16.04
      env: TOXENV=py27
      #- os: linux
      #  language: python
      #  python: 3.5
      #  dist: xenial  # Ubuntu 16.04
      #  env: TOXENV=py35
    - os: linux
      language: python
      python: 3.6
      dist: bionic  # Ubuntu 18.04
      env: TOXENV=py36
    - os: linux
      language: python
      python: 3.7
      dist: bionic  # Ubuntu 18.04
      env: TOXENV=py37
    - os: linux
      language: python
      python: 3.8
      dist: bionic  # Ubuntu 18.04
      env: TOXENV=py38
    - os: osx
      osx_image: xcode10.3
      language: generic
      env: TOXENV=py37
      addons:
        homebrew:
          # update: true
          packages: openslide
      before_install:
        # - brew update && brew install git-lfs
        - pip3 install virtualenv
        - virtualenv -p python3 ~/venv
        - source ~/venv/bin/activate
      #before_install:
      #  # - brew update && brew install git-lfs
      #  - "pyenv install 3.6.8"
      #  - "pyenv global 3.6.8"
      #before_script:
      #  - git lfs install
      #  - git lfs pull
    - os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      # https://github.com/skvark/opencv-python/issues/263
      before_install:
        - choco install -y python --version 3.7.0
        - python -m pip install --upgrade pip
        - choco install -y opencv
      env:
        - TOXENV=py37
        - PATH=/c/Python37:/c/Python37/Scripts:%OPENCV_DIR%/bin:$PATH
  # https://towardsdatascience.com/extensive-python-testing-on-travis-ci-4c24db9bf961
  allow_failures:
    - os: osx
    - os: windows

# See http://docs.travis-ci.com/user/caching/#pip-cache
cache: pip

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      sudo apt-get install openslide-tools ;
    fi

  - if [ "$TRAVIS_PYTHON_VERSION" == "2.7" ]; then
      cp requirements-py27.txt requirements-ci.txt ;
    else
      cp requirements.txt requirements-ci.txt ;
    fi

install:
  - pip install "setuptools<46" -U  # v46 crashes openslide-python install
  - pip install -r requirements-ci.txt
  - pip install -r ./tests/requirements.txt
  - pip --version ; pip list

script:
  # integration
  - tox -v --sitepackages
  # sample run
  - mkdir results && touch configs/sample_config.yaml
  - python bm_experiments/bm_comp_perform.py -o ./results -n 1
  - python birl/bm_template.py -t ./data-images/pairs-imgs-lnds_mix.csv -o ./results --visual --unique -cfg configs/sample_config.yaml
  - rm ./data-images/*_/*/*_HE.csv  # remove target landmarks from histol. tissue
  - python birl/bm_template.py -n anhir -t ./data-images/pairs-imgs-lnds_histol.csv -d ./data-images -o ./results --preprocessing matching-rgb gray -cfg configs/sample_config.yaml
  - python bm_experiments/evaluate_experiment.py -d ./data-images -e ./results/BmTemplate_anhir --visual

after_success:
  - coverage report
  - codecov

notifications:
  email: false
