# vim ft=yaml

# After changing this file, check it on:
#   http://yaml-online-parser.appspot.com/

# See doc/travis_notes.txt for some guidelines

# this file is *not* meant to cover or endorse the use of travis, but rather to
# help confirm pull requests to this project.

dist: xenial  # Ubuntu 16.04

env:
  global:
    - DISPLAY=""

language: python

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37

# See http://docs.travis-ci.com/user/caching/#pip-cache
cache: pip

install:
  - sudo apt-get install openslide-tools
  - pip install -r requirements.txt
  - pip install -r ./tests/requirements.txt
  - pip install tox
  - pip --version ; pip list

script:
  # integration
  - tox -v --sitepackages
  # sample run
  - mkdir results && touch configs/sample_config.yaml
  - python bm_experiments/bm_comp_perform.py -o ./results -n 1
  - python birl/bm_template.py -t ./data_images/pairs-imgs-lnds_mix.csv -o ./results --visual --unique -cfg configs/sample_config.yaml
  - rm ./data_images/*_/*/*_HE.csv  # remove target landmarks from histol. tissue
  - python birl/bm_template.py -t ./data_images/pairs-imgs-lnds_histol.csv -d ./data_images -o ./results --preprocessing matching-rgb gray -cfg configs/sample_config.yaml
  - python bm_experiments/evaluate_experiment.py -d ./data_images -e ./results/BmTemplate --visual

after_success:
  - coverage report
  - codecov

notifications:
  email: false
