# vim ft=yaml

# After changing this file, check it on:
#   http://yaml-online-parser.appspot.com/

# See doc/travis_notes.txt for some guidelines

# this file is *not* meant to cover or endorse the use of travis, but rather to
# help confirm pull requests to this project.

env:
  global:
    - DISPLAY=""

language: python

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36

install:
  - sudo apt-get install python-opencv openslide-tools
  - pip install -r requirements.txt
  - pip install tox

script: tox coverage

after_success:
  - coverage report
  - codecov

notifications:
  email: false
