SIFT: false

bUnwarpJ:
  mode: 1  # 0-2 (0-Accurate, 1-Fast, 2-Mono)
  subsampleFactor: 2  # 0-7 (0 = 2^0, 7 = 2^7)
  minScale: 0  # 0-3 (0-Very Coarse, 1-Coarse, 2-Fine, 3-Very Fine)
  maxScale: 3  # 0-4 (0-Very Coarse, 1-Coarse, 2-Fine, 3-Very Fine, 4-Super Fine)
  # weight to penalize divergence (Ex. 0.1)
  divWeight: 0.1
  # weight to penalize curl (Ex. 0.1)
  curlWeight: 0.1
  # weight to penalize landmark location error (Ex. 1.0)
  landmarkWeight: 0.0
  # weight to penalize intensity difference (Ex. 1.0)
  imageWeight: 1.0
  # weight to penalize consistency difference (Ex. 1.0)
  consistencyWeight: 10.0
  # error function stopping threshold value (Ex. 0.01)
  stopThreshold: 0.01
