SIFT: false

bUnwarpJ:
  mode: 1
  subsampleFactor: 2
  minScale: 0
  maxScale: 3
  divWeight: 0.1
  curlWeight: 0.1
  landmarkWeight: 0.0
  imageWeight: 1.0
  consistencyWeight: 10.0
  stopThreshold: 0.01