RVSS:
  shrinkingConstraint: 1  # (0 to use reference image, or 1 to use shrinking constraint mode)
  # Index of the features extraction model
  featuresModelIndex: 2  # (0=TRANSLATION, 1=RIGID, 2=SIMILARITY, 3=AFFINE)
  # Index of the registration model (0=TRANSLATION, 1=RIGID, 2=SIMILARITY, 3=AFFINE, 4=ELASTIC, 5=MOVING_LEAST_SQUARES)
  registrationModelIndex: 3

SIFT:
  # initial Gaussian blur sigma (SIFT parameter, ex. 1.6)
  initialSigma: 1.6
  # steps per scale octave (SIFT parameter, ex. 3)
  steps: 3
  # minimum image size in pixels (SIFT parameter, ex. 64)
  minOctaveSize: 64
  # maximum image size in pixels (SIFT parameter, ex. 1024)
  maxOctaveSize: 1024
  # feature descriptor size (SIFT parameter, ex. 4)
  fdSize: 8
  # feature descriptor orientation bins (SIFT parameter, ex. 8)
  fdBins: 8
  # closest/next closest ratio (SIFT parameter, ex. 0.92)
  rod: 0.92
  # maximal alignment error in pixels (SIFT parameter, ex. 25)
  maxEpsilon: 25
  # inlier ratio (SIFT parameter, ex. 0.05)
  minInlierRatio: 0.05
  # expected transformation (SIFT parameter, 0:Translation, 1:Rigid, 2:Similarity, 3:Affine, 4:Perspective)
  modelIndex: 1
