name: Install package

# see: https://help.github.com/en/actions/reference/events-that-trigger-workflows
on:  # Trigger the workflow on push or pull request,  but only for the master branch
  push:
    branches: [master]
  pull_request: {}

jobs:
  pkg-check:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Check package
        run: |
          pip install check-manifest
          check-manifest
          python setup.py check --metadata --strict
          python setup.py install --dry-run --user

      - name: Create package
        run: |
          pip install --upgrade setuptools wheel
          python setup.py sdist bdist_wheel

      - name: Verify package
        run: |
          pip install twine==3.2
          twine check dist/*
          python setup.py clean

  pkg-install:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macOS-10.15]  # , windows-2019
        python-version: [3.7]

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Create package
        run: |
          python setup.py sdist

      - name: Install package
        run: |
          pip install virtualenv
          virtualenv vEnv
          source vEnv/bin/activate
          pip install dist/*
          cd .. & python -c "import birl ; print(birl.__version__)"
          deactivate
          rm -rf vEnv
